services:
  api:
    build: "Api/."
    image: "dev/completeapi/api:${tag}"
    container_name: api
    ports:
      - "4000:4001"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  calculator:
    build: "Calculator/."
    image: "dev/completeapi/calculator:${tag}"
    container_name: calculator
    ports:
      - "6000:6001"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    container_name: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3