services:
  completeapi:
    build: .
    image: "dev/completeapi/api1:${tag}"
    container_name: api1
    ports:
      - "4000:4001"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"